on: [push]
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          browser: 'chrome'
          robot_reports_dir: public
          robot_tests_dir: Tests
  generate_report:
        if: always()
        needs: [robot_test]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2.3
          with:
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        
        

